version: '3.8'
services:
  db: 
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - '5431:5432'
  bot:
    build: .
      #command: sh -c "alembic upgrade head && python app.py"
    command: sh -c "python test.py"
    env_file:
      - .env
    restart: always
    depends_on:
      - db

volumes:
  postgres-data:
